// Demo data for Twin demo mode — 50 fake contacts with realistic Moroccan business conversations

const BASE = new Date('2026-06-22T12:00:00Z').getTime();

function ts(daysAgo, h, m = 0) {
  const d = new Date(BASE);
  d.setDate(d.getDate() - daysAgo);
  d.setHours(h, m, 0, 0);
  return Math.floor(d.getTime() / 1000);
}

function i(daysAgo, h, m, fromMe, body) {
  return { timestamp: ts(daysAgo, h, m), fromMe, body };
}

// ── 5 active contacts (will appear in inbox after demo sync) ───────────────────

const ACTIVE = [
  {
    name: 'Ahmed Benali',
    phone: '212661234501',
    category: 'customer',
    inboxStatus: 'needs_reply',
    msgs: [
      i(45, 10, 15, false, 'السلام عليكم، بغيت نعرف واش عندكم قفطان أخضر في المقاس L'),
      i(45, 10, 22, true,  'وعليكم السلام أحمد! نعم عندنا، السعر 450 درهم'),
      i(45, 10, 35, false, 'واش غادي تكون متوفرة الأسبوع الجاي؟'),
      i(45, 10, 41, true,  'نعم، عندنا في المستودع دابا. تقدر تجي تشوفها؟'),
      i(45, 11,  5, false, 'غادي نجي غدا إن شاء الله'),
      i(44, 14, 30, false, 'جيت ومعجبتنيش الخضرة، واش عندكم لون ثاني؟'),
      i(44, 14, 45, true,  'عندنا أزرق كحلي، لرمادي، واللي يجي الجمعة هو القهوي - كلهم 450'),
      i(44, 15,  0, false, 'واش تقدر دير ليا ريزيرفاسيون على القهوي؟'),
      i(44, 15,  5, true,  'بلا مشكيل، خليت عليك واحدة في المقاس L'),
      i(30,  9, 20, false, 'السلام، جيت باش ناخد الواحدة القهوي'),
      i(30,  9, 25, true,  'مرحبا أحمد! كلشي واضح، غادي تكون جاهزة دابا'),
      i(30, 10, 15, false, 'خدتها، شكرا بزاف - جودة عالية'),
      i(30, 10, 18, true,  'شكرا على ثقتك! أي وقت خدمتنا'),
      i(15, 11, 30, false, 'السلام أخي، كاين شي جديد عندكم؟'),
      i(15, 11, 45, true,  'أيه، وصلتنا كوليكسيون جديدة للصيف - جلابيب وقفاطن'),
      i(15, 12,  0, false, 'شحال الثمن؟'),
      i(15, 12,  5, true,  'الجلابيب من 350 إلى 600 حسب الجودة، والقفاطن من 400 إلى 850'),
      i(15, 12, 30, false, 'بغيت نشري 5 قطع للعرس، واش كاين ريدوكسيون؟'),
      i(15, 12, 45, true,  'على 5 قطع نعطيك 10% تخفيض'),
      i(15, 13,  0, false, 'مزيان! غادي نجي الأسبوع الجاي'),
      i( 2,  9, 15, false, 'السلام! جيت - بغيت 100 وحدة للجملة، كاين تخفيض أكبر؟'),
      i( 2,  9, 30, true,  'مرحبا أحمد! نعم، على 100 وحدة نعطيك 25% - السعر الجملة 337 درهم للواحدة'),
      i( 2,  9, 45, false, 'واش تقدر تبعتها لكاسا؟ ومتى؟'),
      i( 2, 10,  0, true,  'نعم، التوصيل 3-5 أيام، رسوم التوصيل 80 درهم على الكمية الكاملة'),
      i( 2, 10, 20, false, 'وطريقة الدفع؟'),
      i( 2, 10, 30, true,  'نقبلو CIH، Attijari، أو CashPlus. تقدر تدفع 50% مسبقا و50% عند الاستلام'),
      i( 2, 10, 45, false, 'واش تقدر تعطيني فاكتورة للتسجيل التجاري؟'),
      i( 2, 11,  0, true,  'بلا مشكيل، كنديرو الفاكتورة بكل التفاصيل'),
      i( 0,  9, 30, false, 'السلام، قررت نشري 100 وحدة - كيفاش نبدا البروسيدور؟'),
    ],
  },
  {
    name: 'Fatima Zahra Alaoui',
    phone: '212662345601',
    category: 'customer',
    inboxStatus: 'draft_ready',
    draftReply: 'السلام عليكم فاطمة الزهراء! أعتذر بشدة عن هذه التجربة السيئة. فهمت الموضوع — الطرد وصل متأخر 5 أيام والمحتوى كان تالف. سنقوم باسترداد كامل المبلغ أو إرسال بديل جديد حسب ما تفضلين. أرجو أن ترسلي صور التلف وسنعالج الأمر خلال 24 ساعة. مع اعتذاراتنا الصادقة.',
    msgs: [
      i(20, 14,  0, false, 'مرحبا، شفت كوليكسيونكم على الإنستغرام وبغيت نشري جلابة'),
      i(20, 14, 15, true,  'أهلاً فاطمة الزهراء! يسعدنا خدمتك، أي موديل عجبك؟'),
      i(20, 14, 30, false, 'الجلابة الزرقة الداكنة - رقم JL-204'),
      i(20, 14, 40, true,  'ممتاز! متوفرة بالأحجام S/M/L. السعر 520 درهم مع التوصيل'),
      i(20, 15,  0, false, 'بغيت M. كيفاش نخلص؟'),
      i(20, 15, 15, true,  'تقدري تخلصي عبر CashPlus أو تحويل بنكي. نبعت ليك التفاصيل'),
      i(20, 16,  0, false, 'خلصت - رقم التحويل: TRF/2026/44521'),
      i(20, 16, 10, true,  'تم التأكيد! الطلب سيُشحن خلال 48 ساعة'),
      i(17, 10,  0, true,  'تتبع شحنتك: AMEX2026453 - التوصيل خلال 2-3 أيام'),
      i(17, 10, 15, false, 'شكرا!'),
      i(12,  9,  0, false, 'السلام، الطلب ما وصلاش بعد - 5 أيام فاتو'),
      i(12,  9, 20, true,  'أعتذر على التأخير! متوقع غدا'),
      i(12, 10,  0, false, 'هذا غير مقبول، طلبتيه للعيد'),
      i(11, 11,  0, false, 'وصل الطرد اليوم لكن الجلابة فيها بقع وكأنها استعملت من قبل!'),
      i(11, 11, 30, true,  'هذا مؤسف جداً! أرسلي صور وسنحل الأمر فوراً'),
      i(11, 12,  0, false, 'أرسلت الصور على الواتساب'),
      i(11, 14,  0, true,  'شوفت الصور - واضح المشكلة. هل تريدين استرداد أم بديل؟'),
      i(11, 14, 30, false, 'بغيت المبلغ كامل راجع'),
      i(10,  9,  0, true,  'بلا مشكيل، الاسترداد سيتم خلال 5-7 أيام عمل'),
      i( 0,  8, 45, false, 'السلام، مرت 10 أيام ما وصلنيش الاسترداد. أين المشكلة؟'),
    ],
  },
  {
    name: 'Youssef Kadiri',
    phone: '212663456701',
    category: 'supplier',
    inboxStatus: 'replied',
    msgs: [
      i(60, 10,  0, false, 'Bonjour, je suis fournisseur de tissus à Fès. Intéressé par une collaboration'),
      i(60, 10, 30, true,  'Bonjour M. Kadiri! Très intéressé. Quels tissus proposez-vous?'),
      i(60, 11,  0, false, 'Brocart, velours et satin - toute la gamme pour jellabas et caftans'),
      i(60, 11, 30, true,  'Excellent. Quels sont vos MOQ?'),
      i(60, 12,  0, false, 'Minimum 50 mètres par tissu. Prix dégressif à partir de 200m'),
      i(60, 14,  0, true,  'Pouvez-vous envoyer un catalogue et vos tarifs?'),
      i(60, 15,  0, false, 'Brocart 45-80 DH/m, velours 60-90 DH/m. Je vous envoie le catalogue'),
      i(45,  9,  0, false, 'Avez-vous reçu le catalogue?'),
      i(45,  9, 30, true,  'Oui reçu. Belle gamme. Pouvez-vous envoyer des échantillons?'),
      i(45, 10,  0, false, '5 échantillons gratuits. Votre adresse?'),
      i(44, 11,  0, false, 'Échantillons expédiés, arrivée sous 3 jours'),
      i(42, 14,  0, true,  'Reçu! La qualité du brocart doré est exceptionnelle'),
      i(42, 14, 30, false, 'Merci! Prix pour 500m de brocart doré?'),
      i(42, 15,  0, true,  '500m: 38 DH/m au lieu de 55 DH. Économie de 8 500 DH'),
      i(30, 10,  0, false, 'Décision: 500m brocart doré + 200m velours bordeaux. Total?'),
      i(30, 10, 30, true,  '19 000 + 12 400 = 31 400 DH. Ou 29 830 avec remise 5% comptant'),
      i(30, 11,  0, false, 'Je prends le paiement comptant. Virement ce soir'),
      i(29,  9,  0, false, 'Virement effectué: 29 830 DH'),
      i(29,  9, 30, true,  'Reçu! Production lancée. Livraison dans 10 jours'),
      i(19, 14,  0, false, 'Livraison aujourd\'hui 14h-18h. Disponible?'),
      i(19, 14, 15, true,  'Oui présent! Merci Youssef'),
      i(19, 17,  0, false, 'Livré avec bon signé. Tout est là?'),
      i(19, 17, 30, true,  'Tout reçu et vérifié. Excellent travail! On refera affaire.'),
    ],
  },
  {
    name: 'Nadia Berrada',
    phone: '212664567801',
    category: 'customer',
    inboxStatus: 'active',
    msgs: [
      i(10, 11,  0, false, 'Bonjour! Je cherche un caftan sur mesure pour mon mariage en août'),
      i(10, 11, 15, true,  'Bonjour Nadia! Félicitations! Budget approximatif?'),
      i(10, 11, 30, false, 'Entre 2000 et 3000 DH. C\'est possible?'),
      i(10, 11, 45, true,  'Absolument! Caftan avec broderies et perles. Vous avez une idée de style?'),
      i(10, 12,  0, false, 'Blanc cassé ou ivoire, broderies dorées. Style classique marocain'),
      i(10, 12, 15, true,  'Parfait! Tissu en satin ou mikado? Broderies main ou machine?'),
      i(10, 13,  0, false, 'Satin et broderies à la main si c\'est dans le budget'),
      i(10, 13, 20, true,  'Satin ivoire + broderies main dorées: 2 800 DH. Délai 6-8 semaines'),
      i(10, 14,  0, false, 'Mon mariage c\'est le 15 août, donc j\'ai le temps. Comment ça marche?'),
      i(10, 14, 15, true,  'On prend vos mesures, vous choisissez le design, 3 essayages inclus'),
      i(10, 15,  0, false, 'Super! Quand puis-je venir pour les mesures?'),
      i(10, 15, 10, true,  'Samedi matin 10h ou dimanche après-midi. Vous préférez?'),
      i(10, 15, 30, false, 'Samedi 10h c\'est parfait!'),
      i(10, 15, 35, true,  'Noté! Apportez des photos de modèles qui vous inspirent'),
      i( 3, 10,  0, false, 'Bonjour! Peut-on ajouter des manches longues en mousseline?'),
      i( 3, 10, 15, true,  '+150 DH. Total 2 950 DH'),
      i( 3, 10, 30, false, 'D\'accord! Et pour la ceinture brodée?'),
      i( 3, 10, 45, true,  'Ceinture assortie incluse dans le prix. À samedi!'),
    ],
  },
  {
    name: 'Mohammed El Alami',
    phone: '212665678901',
    category: 'customer',
    inboxStatus: 'needs_reply',
    msgs: [
      i( 1, 14,  0, false, 'السلام عليكم، شفت محلكم ف المولى وأعجبني'),
      i( 1, 14, 15, true,  'وعليكم السلام محمد! يسعدنا ذلك. شنو بغيت؟'),
      i( 1, 14, 30, false, 'عندي عرس لبنتي الشهر الجاي وبغيت جلابة وقفطان للعريسة'),
      i( 1, 14, 45, true,  'مبروك! عندنا كوليكسيون كاملة للعرسان. الأثمنة؟'),
      i( 1, 15,  0, false, 'نعم، بغيت نعرف قبل الأثمنة'),
      i( 1, 15, 10, true,  'جلابة العروسة من 1200 إلى 3500 حسب التطريز، والقفطان من 1500 إلى 5000'),
      i( 1, 15, 30, false, 'وكمتى تكون جاهزة؟ عندنا العرس 20 يوليوز'),
      i( 1, 15, 45, true,  'موديلات جاهزة للتسليم الفوري، أو على القياس 3-4 أسابيع'),
      i( 0, 10, 15, false, 'واش تقدر تعطيني لعنوانو لنمشي نشوفو؟ غادي نجي مع مرتي'),
    ],
  },
];

// ── 45 brief contacts (bulk of sync animation) ─────────────────────────────────

function brief(name, phone, msgs) {
  return { name, phone, category: 'customer', msgs };
}

const PASSIVE = [
  brief('Karim Cherkaoui', '212661100001', [
    i(90, 10, 0, false, 'السلام، شحال الجلابة البيضاء المطرزة؟'),
    i(90, 10, 30, true, '350 درهم مع التطريز اليدوي'),
    i(90, 11, 0, false, 'مزيان، غادي نجي غدا إن شاء الله'),
    i(89, 14, 0, false, 'جيت وخدت واحدة، شكرا بزاف'),
    i(89, 14, 10, true,  'شكرا كريم! أي وقت خدمتنا'),
  ]),
  brief('Houda Meziani', '212661100002', [
    i(85, 9, 0, false, 'Bonjour, avez-vous des jellabas en soie?'),
    i(85, 9, 20, true,  'Bonjour! Nous avons de la soie naturelle et artificielle. Budget?'),
    i(85, 9, 40, false, 'Entre 600 et 900 DH'),
    i(85, 10, 0, true,  'Parfait! Soie artificielle 650 DH, soie naturelle 890 DH'),
    i(85, 10, 20, false, 'Je prends la naturelle. Je passe samedi'),
  ]),
  brief('Rachid Benhaddou', '212661100003', [
    i(80, 11, 0, false, 'كاين عندكم قفطان نسائي للأعراس؟'),
    i(80, 11, 15, true,  'نعم، كوليكسيون كاملة من 800 إلى 2500 درهم'),
    i(80, 11, 30, false, 'بغيت ديال 1200 للزوجة'),
    i(80, 12, 0, true,  'ممتاز! عندنا 5 موديلات في هاد الثمن'),
    i(80, 14, 0, false, 'خدنا واحدة، شكرا. جودة ممتازة'),
    i(80, 14, 5, true,  'شكرا راشد! نتمنى ترجعو'),
  ]),
  brief('Samira Lahrichi', '212661100004', [
    i(78, 14, 0, false, 'Salam, est-ce que vous livrez à Marrakech?'),
    i(78, 14, 20, true,  'Oui! Livraison à Marrakech 2-3 jours, 60 DH'),
    i(78, 14, 40, false, 'Super! Je commande 2 jellabas taille M'),
    i(78, 15, 0, true,  'Parfait! Total 780 DH + 60 livraison = 840 DH'),
    i(77,  9, 0, false, 'Reçu! Très belles. Je recommanderai'),
  ]),
  brief('Omar Bensouda', '212661100005', [
    i(75, 10, 0, false, 'السلام، كاين تخفيض للجملة؟'),
    i(75, 10, 15, true,  'نعم، +10 قطع 15%، +25 قطع 20%، +50 قطع 25%'),
    i(75, 10, 30, false, 'بغيت 20 جلابة رجالية، أسعار الجملة؟'),
    i(75, 11, 0, true,  '20 قطع × 280 × 85% = 4760 درهم. التوصيل مجاني'),
    i(75, 11, 30, false, 'متفقين، غادي نخلص اليوم'),
    i(74, 9, 0, true,  'تم استلام الدفع! التوصيل غدا'),
  ]),
  brief('Leila Hajji', '212661100006', [
    i(72, 13, 0, false, 'Bonjour! J\'ai commandé il y a 5 jours, où est ma commande?'),
    i(72, 13, 20, true,  'Bonjour Leila! Votre commande #2891 est en route. Suivi: MA44712'),
    i(72, 13, 40, false, 'D\'accord, merci pour le suivi'),
    i(71, 10, 0, false, 'Reçu ce matin! C\'est magnifique, merci beaucoup'),
    i(71, 10, 10, true,  'Merci Leila! N\'hésitez pas à revenir'),
  ]),
  brief('Hassan Mouktadir', '212661100007', [
    i(70, 9, 0, false, 'واش عندكم جلابة رجالية في مقاس XXL؟'),
    i(70, 9, 20, true,  'نعم، عندنا حتى مقاس XXXL. شنو تبغي؟'),
    i(70, 9, 40, false, 'جلابة بيضاء للصلاة، XXL'),
    i(70, 10, 0, true,  'عندنا بيضاء وإيفواري، الثمن 320 درهم'),
    i(70, 10, 20, false, 'البيضاء - غادي نجي الجمعة'),
  ]),
  brief('Zineb Fassi', '212661100008', [
    i(68, 15, 0, false, 'Bonsoir! Je cherche un caftan pour une fête de mariage'),
    i(68, 15, 15, true,  'Bonsoir Zineb! Invitée ou mariée?'),
    i(68, 15, 30, false, 'Invitée. Budget 600-900 DH'),
    i(68, 15, 45, true,  'Plusieurs modèles disponibles. Couleur préférée?'),
    i(68, 16, 0, false, 'Rouge ou bordeaux'),
    i(68, 16, 15, true,  'Parfait choix! Venez voir, nous avons 8 modèles dans ces teintes'),
  ]),
  brief('Abderrahim Tazi', '212661100009', [
    i(65, 10, 0, false, 'السلام، الجلابة اللي خدتها عندها مشكيل في التطريز'),
    i(65, 10, 20, true,  'أهلاً! أرسل صورة من فضلك'),
    i(65, 10, 40, false, 'أرسلت - الخيط منحل في الجانب الأيسر'),
    i(65, 11, 0, true,  'أعتذر! أرجع الجلابة ونصلحها مجاناً أو نبدلها'),
    i(65, 11, 20, false, 'شكرا، غادي نجي غدا بالجلابة'),
    i(64, 14, 0, true,  'تم التبديل، شكرا لثقتك راشد'),
  ]),
  brief('Malika Znati', '212661100010', [
    i(62, 11, 0, false, 'Bonjour! Je veux un caftan personnalisé avec initiales brodées'),
    i(62, 11, 20, true,  'Bonjour! Tout à fait possible. Délai 2 semaines, supplément 150 DH'),
    i(62, 11, 40, false, 'C\'est pour un cadeau d\'anniversaire dans 3 semaines. OK'),
    i(62, 12, 0, true,  'On commençe demain! Vos mesures et les initiales?'),
    i(62, 12, 20, false, 'T42 et les initiales M.Z. en or'),
  ]),
  brief('Jamal Ouardi', '212661100011', [
    i(60, 9, 0, false, 'كاين عندكم جلابة للأطفال؟'),
    i(60, 9, 20, true,  'نعم، من مقاس 2 سنين إلى 14 سنة. الأثمنة من 150 إلى 280'),
    i(60, 9, 40, false, 'بغيت لولد 8 سنين ولبنت 10 سنين'),
    i(60, 10, 0, true,  '2 جلابة أطفال: 180 + 200 = 380 درهم'),
    i(60, 10, 20, false, 'متفقين، غادي نجي العصيرة'),
  ]),
  brief('Khadija Benchekroun', '212661100012', [
    i(58, 14, 0, false, 'Salam, est-ce que vous acceptez les retours?'),
    i(58, 14, 20, true,  'Oui! 7 jours pour échanger, article non porté et étiquette intacte'),
    i(58, 14, 40, false, 'Parfait, j\'ai une taille M mais je pense que L serait mieux'),
    i(58, 15, 0, true,  'Pas de problème! Apportez l\'article et on échange'),
    i(57, 10, 0, false, 'Échangé! La L est parfaite, merci'),
  ]),
  brief('Said El Mansouri', '212661100013', [
    i(55, 10, 0, false, 'السلام، شفت إعلانكم على الفيسبوك'),
    i(55, 10, 20, true,  'أهلاً سعيد! يسعدنا. شنو يعجبك من كوليكسيوننا؟'),
    i(55, 10, 40, false, 'الجلابة الزرقة اللي في الصورة - شحال ثمنها؟'),
    i(55, 11, 0, true,  'هادي JB-117 - 420 درهم للرجال، متوفرة'),
    i(55, 11, 20, false, 'معقولة، غادي نجي نشوفها'),
  ]),
  brief('Latifa Bouziane', '212661100014', [
    i(52, 15, 0, false, 'Bonsoir! Livrez-vous à l\'étranger (France)?'),
    i(52, 15, 20, true,  'Bonsoir! Oui, livraison France 7-12 jours via DHL, 180 DH'),
    i(52, 15, 40, false, 'Je veux commander 3 caftans pour ma famille là-bas'),
    i(52, 16, 0, true,  'Parfait! Pour 3 articles à 1 200 DH, total avec livraison 3 780 DH'),
    i(52, 16, 20, false, 'D\'accord, je commande. Comment payer depuis l\'étranger?'),
    i(52, 16, 40, true,  'Western Union ou virement international. Je vous envoie les détails'),
  ]),
  brief('Driss Seffar', '212661100015', [
    i(50, 9, 0, false, 'السلام، عندكم شي عروض للعيد؟'),
    i(50, 9, 20, true,  'نعم! تخفيضات 20% على كل الكوليكسيون حتى الجمعة'),
    i(50, 9, 40, false, 'ممتاز! غادي نجي اليوم العصيرة مع العيلة'),
    i(50, 14, 0, false, 'جينا وخدنا 4 جلابيب، شكرا على التخفيض'),
    i(50, 14, 10, true,  'شكرا درييس! عيدكم مبارك'),
  ]),
  brief('Aicha Tazi', '212661100016', [
    i(48, 11, 0, false, 'Bonjour! Avez-vous des caftans de mariage sur stock?'),
    i(48, 11, 20, true,  'Oui! 12 modèles disponibles immédiatement. Votre taille?'),
    i(48, 11, 40, false, 'Taille 38. Budget max 2 000 DH'),
    i(48, 12, 0, true,  '4 modèles disponibles en T38 sous 2 000 DH'),
    i(48, 12, 20, false, 'Je passe demain matin pour voir'),
  ]),
  brief('Khalid El Idrissi', '212661100017', [
    i(46, 10, 0, false, 'مرحبا، بغيت نشري جلابة لوالدي كهدية'),
    i(46, 10, 20, true,  'أهلاً! عمره؟ ومقاسه التقريبي؟'),
    i(46, 10, 40, false, '70 سنة، عادةً L أو XL'),
    i(46, 11, 0, true,  'عندنا جلابة رجالية كلاسيكية مناسبة جداً لهذا السن، من 300 إلى 500'),
    i(46, 11, 20, false, 'غادي ناخد ديال 400، اللون الفيل'),
    i(46, 11, 40, true,  'اختيار ممتاز! هغلفوها كهدية مجاناً'),
  ]),
  brief('Naima Ghali', '212661100018', [
    i(44, 14, 0, false, 'Salam! Les photos sur Instagram sont magnifiques. Vous livrez à Rabat?'),
    i(44, 14, 20, true,  'Merci! Oui, Rabat 2 jours, 45 DH'),
    i(44, 14, 40, false, 'Je veux une jellaba beige, taille S'),
    i(44, 15, 0, true,  '3 teintes de beige disponibles. Je vous envoie les photos'),
    i(44, 15, 20, false, 'J\'aime le beige doré. Je commande!'),
  ]),
  brief('Soufiane Darif', '212661100019', [
    i(42, 9, 0, false, 'السلام، كيفاش الأداء؟ واش تقبلو البطاقة البنكية؟'),
    i(42, 9, 20, true,  'نقبلو CMI في المحل، أو CashPlus وتحويل للأونلاين'),
    i(42, 9, 40, false, 'مزيان، غادي نجي اليوم'),
    i(42, 14, 0, false, 'جيت وخدت جوج جلابيب بالبطاقة، شكرا'),
  ]),
  brief('Fatna Lahlou', '212661100020', [
    i(40, 13, 0, false, 'Bonjour! Est-ce que vous faites des jallabiyas pour nourrissons?'),
    i(40, 13, 20, true,  'Bonjour! Oui, de la naissance à 24 mois. Très mignon pour les occasions'),
    i(40, 13, 40, false, 'Pour un baptême, bébé de 3 mois. Budget 200 DH'),
    i(40, 14, 0, true,  'Nous avons de belles pièces blanches avec broderies dans ce budget'),
    i(40, 14, 20, false, 'Je passe en fin de semaine'),
  ]),
  brief('Hicham Guerraoui', '212661100021', [
    i(38, 10, 0, false, 'السلام، كاين عندكم أثواب للتدريس؟'),
    i(38, 10, 20, true,  'أهلاً هشام! عندنا قفاطن وجلابيب رسمية مناسبة. ثمن التدريس؟'),
    i(38, 10, 40, false, 'الثمن الوسطي، شي 500-700'),
    i(38, 11, 0, true,  'عندنا كوليكسيون ممتازة في هاد النطاق'),
    i(38, 11, 20, false, 'غادي نجي'),
  ]),
  brief('Souad Benjelloun', '212661100022', [
    i(36, 16, 0, false, 'Bonsoir! Je veux un costume complet pour mon mari pour un mariage'),
    i(36, 16, 20, true,  'Bonsoir! Jellaba + babouches assortis? Budget approximatif?'),
    i(36, 16, 40, false, '1 500 DH pour tout'),
    i(36, 17, 0, true,  'C\'est faisable! Jellaba 900 DH + babouches 250 DH + ceinture 150 = 1 300 DH'),
    i(36, 17, 20, false, 'Parfait! On vient samedi en famille'),
  ]),
  brief('Yassine Benkirane', '212661100023', [
    i(34, 9, 0, false, 'مرحبا، واش عندكم تسليم السريع في كاسا؟'),
    i(34, 9, 20, true,  'نعم، بين الأحياء 2-3 ساعات، الثمن 35 درهم'),
    i(34, 9, 40, false, 'كاين عندكم جلابة رمادية XL؟'),
    i(34, 10, 0, true,  'نعم! عندنا رمادي فاتح ورمادي غامق في XL'),
    i(34, 10, 20, false, 'بعثلي الرمادي الغامق، غادي نخلص بالتوصيل'),
    i(33, 15, 0, true,  'وصلت؟ كيفاش عجبتك؟'),
    i(33, 15, 30, false, 'عجبتني بزاف شكرا!'),
  ]),
  brief('Hafida Sekkat', '212661100024', [
    i(32, 11, 0, false, 'Bonjour! Vous faites des remboursements si je ne suis pas satisfaite?'),
    i(32, 11, 20, true,  'Bonjour! Oui, remboursement complet sous 14 jours si défaut'),
    i(32, 11, 40, false, 'C\'est rassurant. Je commande 2 caftans alors'),
    i(32, 12, 0, true,  'Avec plaisir! Quels modèles vous intéressent?'),
    i(32, 12, 20, false, 'Le CF-301 en bleu et le CF-412 en bordeaux, taille 40'),
  ]),
  brief('Mehdi Alaoui', '212661100025', [
    i(30, 10, 0, false, 'السلام، واش عندكم فروع في فاس؟'),
    i(30, 10, 20, true,  'حالياً محل واحد في الدار البيضاء، لكن نبعتو لكل المغرب'),
    i(30, 10, 40, false, 'مزيان، بغيت نطلب أونلاين، كيفاش؟'),
    i(30, 11, 0, true,  'واتساب أو انستغرام - صورة الموديل والمقاس والمدينة'),
    i(30, 11, 20, false, 'شكرا، غادي نبعثلك اختيارتي هاد الليلة'),
  ]),
  brief('Rokia Tazi', '212661100026', [
    i(28, 14, 0, false, 'Bonjour! Mon caftan acheté ici a rétréci au lavage'),
    i(28, 14, 20, true,  'Bonjour Rokia! C\'est nos caftans recommandés lavage à la main froide'),
    i(28, 14, 40, false, 'Je l\'ai mis en machine... c\'est ma faute donc'),
    i(28, 15, 0, true,  'On peut essayer de le détendre. Apportez-le et on voit'),
    i(28, 15, 20, false, 'Merci pour votre gentillesse! Je passe demain'),
  ]),
  brief('Amine El Filali', '212661100027', [
    i(26, 9, 0, false, 'السلام، كاين عندكم جلابة للحجاج؟'),
    i(26, 9, 20, true,  'نعم، جلابة الإحرام البيضاء وجلابيب الصلاة من 200 إلى 350'),
    i(26, 9, 40, false, 'بغيت جوج - واحدة للحج وواحدة للعمرة'),
    i(26, 10, 0, true,  '2 جلابيب بيضاء إحرام: 500 درهم، التغليف مجاناً'),
    i(26, 10, 20, false, 'حجزتهم، غادي نجي باكر'),
  ]),
  brief('Widad Chraibi', '212661100028', [
    i(24, 15, 0, false, 'Salam! Je cherche un caftan pour la fête du trône'),
    i(24, 15, 20, true,  'Salam Widad! Très bonne occasion! Vous voulez quelque chose de classique ou moderne?'),
    i(24, 15, 40, false, 'Classique mais avec une touche moderne. Couleur verte ou dorée'),
    i(24, 16, 0, true,  'Nous avons exactement ça - un caftan en satin vert avec broderies dorées'),
    i(24, 16, 20, false, 'Ooh magnifique! Je viens voir demain'),
  ]),
  brief('Zakaria Temsamani', '212661100029', [
    i(22, 10, 0, false, 'السلام، كيف نقدر نعرف أن الجلابة فيها تطريز يدوي وماشي آلة؟'),
    i(22, 10, 20, true,  'سؤال ممتاز! التطريز اليدوي فيه حبات ناشزة قليلاً، والنقشات مش منتظمة 100%'),
    i(22, 10, 40, false, 'شكرا على التوضيح، هادو اللي بغيت نتجنب - بغيت اليدوي'),
    i(22, 11, 0, true,  'كل جلاباتنا الفوق 400 درهم يدوية كاملاً - عندنا الشهادة'),
    i(22, 11, 20, false, 'ممتاز، غادي نجي الجمعة نشوف الكوليكسيون'),
  ]),
  brief('Loubna El Fassi', '212661100030', [
    i(20, 13, 0, false, 'Bonjour! Vendez-vous aussi des babouches?'),
    i(20, 13, 20, true,  'Oui! Babouches artisanales en cuir Beldi, 200-450 DH selon le modèle'),
    i(20, 13, 40, false, 'Est-ce que ça se commande en ligne aussi?'),
    i(20, 14, 0, true,  'Bien sûr! Pointure et modèle par message et on expédie'),
    i(20, 14, 20, false, 'Parfait! Je vais choisir et vous écrire ce soir'),
  ]),
  brief('Bilal Benchekroun', '212661100031', [
    i(18, 9, 0, false, 'سلام، بغيت أعرف إذا كاين جلابة من الصوف الأصلي'),
    i(18, 9, 20, true,  'نعم! صوف جوتي 100% من الجبال، دافي ومريح. من 600 درهم'),
    i(18, 9, 40, false, 'ممتاز، هاد النوع نبغيه للشتاء. عندكم في اللون الكحلي؟'),
    i(18, 10, 0, true,  'كحلي متوفر في L وXL. غادي نحجز ليك؟'),
    i(18, 10, 20, false, 'حجز L من فضلك'),
  ]),
  brief('Hayat Laroui', '212661100032', [
    i(16, 14, 0, false, 'Bonjour! J\'ai besoin d\'un caftan pour un mariage dans 10 jours. Possible?'),
    i(16, 14, 20, true,  'Bonjour Hayat! En stock nous pouvons faire ça! Quelle taille?'),
    i(16, 14, 40, false, 'Taille 44. J\'aime le rouge ou le fuchsia'),
    i(16, 15, 0, true,  'Nous avons un fuchsia magnifique en T44. Voulez-vous voir une photo?'),
    i(16, 15, 20, false, 'Oui s\'il vous plaît! C\'est pour quoi prix?'),
    i(16, 15, 40, true,  '1 400 DH. Photo envoyée'),
    i(16, 16, 0, false, 'Il est superbe! Je le prends, je passe demain payer'),
  ]),
  brief('Tariq Benali', '212661100033', [
    i(14, 10, 0, false, 'السلام، جاء عندكم شي وصفة جديدة للباقي الشهر؟'),
    i(14, 10, 20, true,  'أهلاً طارق! وصلتنا 3 موديلات جديدة من فاس الأسبوع الماضي'),
    i(14, 10, 40, false, 'غادي نجي نتفرج هاد الأسبوع'),
    i(14, 11, 0, true,  'ننتظرك! وبغيت نبشر - غادي نفتحو فرع ثاني قريبا'),
    i(14, 11, 20, false, 'مبروك! أين؟'),
    i(14, 11, 40, true,  'في عين السبع - الشهر الجاي إن شاء الله'),
  ]),
  brief('Rhita Guerrouaz', '212661100034', [
    i(12, 15, 0, false, 'Salam! Quelle est la différence entre un caftan et une takchita?'),
    i(12, 15, 20, true,  'La takchita est en deux pièces (robe + veste), le caftan en une pièce. La takchita est plus solenelle'),
    i(12, 15, 40, false, 'Ah je comprends! Pour un mariage de famille quelle est la plus appropriée?'),
    i(12, 16, 0, true,  'La takchita pour la mariée ou hôte d\'honneur, caftan pour invitées'),
    i(12, 16, 20, false, 'Super! Je suis invitée donc caftan. Je viens voir votre sélection'),
  ]),
  brief('Ayoub El Morabiti', '212661100035', [
    i(11, 9, 0, false, 'السلام، كاين عندكم قفطان للرجال كيلبسوه في رمضان؟'),
    i(11, 9, 20, true,  'أهلاً أيوب! قفطان رجالي للتهجد والإفطار - من 380 إلى 700'),
    i(11, 9, 40, false, 'بغيت ديال 500 في اللون الأزرق الفاتح'),
    i(11, 10, 0, true,  'عندنا واحد ممتاز! حجزتيه'),
    i(11, 10, 20, false, 'شكرا، غادي نجي الغد'),
  ]),
  brief('Nezha Berrada', '212661100036', [
    i(10, 14, 0, false, 'Bonjour! Vous faites des réductions pour les achats en groupe?'),
    i(10, 14, 20, true,  'Oui! Groupe de 5+ personnes: 15% de remise collective'),
    i(10, 14, 40, false, 'On est 7 amies qui veulent des caftans pour une soirée'),
    i(10, 15, 0, true,  'C\'est parfait! 15% pour vous toutes. Quand voulez-vous venir?'),
    i(10, 15, 20, false, 'Vendredi soir si possible'),
    i(10, 15, 40, true,  'Vendredi 18h-20h, je vous réserve le showroom!'),
  ]),
  brief('Adil Lahlou', '212661100037', [
    i( 9, 10, 0, false, 'السلام، شريت جلابة والقياس ما صلحش - شحال كبيرة في الكتف'),
    i( 9, 10, 20, true,  'مرحبا! هادا ممكن نصلحوه. جيب الجلابة ونضيقو الكتف بلا زيادة'),
    i( 9, 10, 40, false, 'بلا مصاريف؟'),
    i( 9, 11, 0, true,  'بلا مصاريف - هادا ضمان الجودة ديالنا'),
    i( 9, 11, 20, false, 'مزيان بزاف! غادي نجي اليوم'),
  ]),
  brief('Btissam Meziani', '212661100038', [
    i( 8, 11, 0, false, 'Bonjour! Je cherche des caftans pour ma boutique. Vous faites du B2B?'),
    i( 8, 11, 20, true,  'Bonjour! Oui, nous travaillons avec des revendeurs. Quantité minimale 10 pièces'),
    i( 8, 11, 40, false, 'Parfait. Je veux voir votre catalogue grossiste'),
    i( 8, 12, 0, true,  'Je vous envoie le catalogue et la liste de prix professionnels'),
    i( 8, 12, 20, false, 'Reçu merci! Je vous recontacte cette semaine'),
  ]),
  brief('Rachid Hajji', '212661100039', [
    i( 7, 9, 0, false, 'السلام، كاين جلابة صيفية خفيفة؟'),
    i( 7, 9, 20, true,  'أيه! كوتون وكتان صيفي خفيف وبارد، من 280 إلى 420'),
    i( 7, 9, 40, false, 'من أي مواد بالضبط الأخف؟'),
    i( 7, 10, 0, true,  'الكتان (lin) هو الأخف والأبرد، متوفر في ألوان فاتحة'),
    i( 7, 10, 20, false, 'خدت واحد من الكتان الأبيض، شكرا'),
  ]),
  brief('Sanaa Mansouri', '212661100040', [
    i( 6, 14, 0, false, 'Bonjour! J\'habite en Belgique. Livraison internationale possible?'),
    i( 6, 14, 20, true,  'Bonjour Sanaa! Oui, Belgique 10-15 jours via EMS, environ 250 DH'),
    i( 6, 14, 40, false, 'Super! Je veux commander 2 caftans pour mes sœurs'),
    i( 6, 15, 0, true,  'Avec plaisir! Dites-moi les modèles, tailles et je vous fais un devis total'),
    i( 6, 15, 20, false, 'CF-201 taille 38 et CF-315 taille 42, les deux en rose'),
  ]),
  brief('Ibrahim Belhaj', '212661100041', [
    i( 5, 10, 0, false, 'السلام، جاء عندكم كوليكسيون خاصة لرأس السنة؟'),
    i( 5, 10, 20, true,  'أهلاً إبراهيم! نعم، وصلتنا كوليكسيون خاصة الأسبوع الماضي بأقمشة لوكس'),
    i( 5, 10, 40, false, 'مزيان! غادي نجي نشوفها'),
    i( 5, 11, 0, true,  'ننتظرك! الكوليكسيون الجديدة في الواجهة'),
    i( 5, 15, 0, false, 'زرت المحل والكوليكسيون روعة! خدت واحدة'),
  ]),
  brief('Wafaa El Alami', '212661100042', [
    i( 4, 15, 0, false, 'Bonsoir! Mon caftan a une odeur de moisi, c\'est possible?'),
    i( 4, 15, 20, true,  'Bonsoir Wafaa! C\'est étrange pour un article neuf. Quand l\'avez-vous acheté?'),
    i( 4, 15, 40, false, 'Il y a 2 semaines mais je ne l\'avais pas encore sorti du sachet'),
    i( 4, 16, 0, true,  'Apportez-le avec le reçu et on l\'échange sans problème'),
    i( 4, 16, 20, false, 'Merci beaucoup! Je passe demain'),
  ]),
  brief('Noureddine Farouk', '212661100043', [
    i( 3, 9, 0, false, 'السلام، واش عندكم مقاسات كبيرة XXL و XXXL؟'),
    i( 3, 9, 20, true,  'أيه! عندنا حتى XXXXL في بعض الموديلات'),
    i( 3, 9, 40, false, 'ممتاز! هادو صعاب نلقاهم في الدكاكين. شحال الثمن؟'),
    i( 3, 10, 0, true,  'نفس الثمن كالمقاسات العادية - 350-600 حسب الجودة'),
    i( 3, 10, 20, false, 'هادا عدل! غادي نجي قريبا'),
  ]),
  brief('Chadia Belkadi', '212661100044', [
    i( 2, 13, 0, false, 'Salam! Je suis influenceuse mode, collaboration possible?'),
    i( 2, 13, 20, true,  'Salam Chadia! Tout à fait intéressant. Combien de followers avez-vous?'),
    i( 2, 13, 40, false, '45K sur Instagram, 12K sur TikTok - niche mode marocaine'),
    i( 2, 14, 0, true,  'Parfait profil! On peut faire un partenariat: produits contre publications. Vous êtes intéressée?'),
    i( 2, 14, 20, false, 'Oui! Envoyez-moi les détails du partenariat'),
  ]),
  brief('Taha Ouahbi', '212661100045', [
    i( 1, 10, 0, false, 'السلام، مشيت العرس الأسبوع الماضي بجلابة شريتها منكم وكنت الأحسن'),
    i( 1, 10, 20, true,  'أهلاً طه! هادا يفرحنا بزاف! شكرا لثقتك'),
    i( 1, 10, 40, false, 'ناس كثير سألوني فين شريتها - عطيتهم رقمكم'),
    i( 1, 11, 0, true,  'مشكور! هاد النوع من التوصية قيمتها كبيرة بالنسبة لينا'),
    i( 1, 11, 20, false, 'غادي نجي قريبا نشوف الجديد'),
    i( 1, 11, 30, true,  'ننتظرك دايماً! وشكرا مجدداً'),
  ]),
  // ── English-speaking customers ──────────────────────────────────────────────
  brief('Sarah Mitchell', '447700900001', [
    i(88, 14,  0, false, 'Hi! I found you on Instagram. Do you ship to the UK?'),
    i(88, 14, 20, true,  'Hello Sarah! Yes, we ship to the UK — takes 7-10 days, around 200 DH shipping'),
    i(88, 14, 40, false, 'Perfect! I\'m looking for a traditional Moroccan caftan for a wedding. Budget around £150'),
    i(88, 15,  0, true,  'That\'s about 1,800 DH — we have beautiful options in that range. What colours do you prefer?'),
    i(88, 15, 20, false, 'Something in deep blue or emerald green'),
    i(88, 15, 40, true,  'Great taste! I\'ll send you photos of our top 3 options in those colours'),
    i(88, 16,  0, false, 'These are stunning! I\'ll take the emerald one, size UK 12 (EU 40)'),
  ]),
  brief('James Thompson', '447700900002', [
    i(83, 10,  0, false, 'Good morning! I\'m a buyer for a boutique in London. Interested in wholesale'),
    i(83, 10, 20, true,  'Good morning James! We work with several UK boutiques. What volume are you considering?'),
    i(83, 10, 40, false, 'Initial order of 50-100 pieces, mix of caftans and jellabas'),
    i(83, 11,  0, true,  'We can do that. Wholesale prices start at 30% below retail. Can I send our catalogue?'),
    i(83, 11, 20, false, 'Yes please. Also, do you have CE/quality certificates?'),
    i(83, 11, 40, true,  'All our artisan pieces come with origin certificates. Catalogue sent to your WhatsApp'),
  ]),
  brief('Emma Clarke', '447700900003', [
    i(77, 16,  0, false, 'Hi! I\'m a fashion content creator with 80K followers — interested in collaboration?'),
    i(77, 16, 20, true,  'Hello Emma! We\'d love that. What kind of collaboration do you have in mind?'),
    i(77, 16, 40, false, 'A styling video + 3 posts featuring your pieces, in exchange for product'),
    i(77, 17,  0, true,  'That works for us! We\'d send you 2-3 pieces to style. Can you share your media kit?'),
    i(77, 17, 20, false, 'Sent it to your DMs on Instagram. Looking forward to working together!'),
  ]),
  brief('Omar Hassan', '201001234567', [
    i(74, 11,  0, false, 'Hello, I\'m from Cairo. Can you ship to Egypt?'),
    i(74, 11, 20, true,  'Hi Omar! Yes, Egypt usually 5-8 days, around 150 DH shipping'),
    i(74, 11, 40, false, 'Great. I want 3 men\'s jellabas in dark colours, size XL'),
    i(74, 12,  0, true,  'We have navy, dark brown and black in XL. 350 DH each, total 1050 + 150 shipping'),
    i(74, 12, 20, false, 'Perfect. How do I pay from Egypt?'),
    i(74, 12, 40, true,  'Western Union or bank transfer to our Attijariwafa account. I\'ll send details'),
  ]),
  brief('Aisha Al-Rashidi', '971501234567', [
    i(71, 13,  0, false, 'Hello! I\'m in Dubai. Do you do custom embroidery with names?'),
    i(71, 13, 20, true,  'Hi Aisha! Yes, we do personalised embroidery. Arabic or Latin letters?'),
    i(71, 13, 40, false, 'Arabic. I want my daughter\'s name on a white caftan for her birthday'),
    i(71, 14,  0, true,  'Beautiful gift! That\'s +200 DH for embroidery. Caftan from 600 DH. Delivery to UAE 10-14 days'),
    i(71, 14, 20, false, 'Can you do it in gold thread?'),
    i(71, 14, 40, true,  'Of course, gold thread is our specialty. I\'ll send you samples of our embroidery work'),
  ]),
  brief('Ryan Collins', '212661200001', [
    i(66, 10,  0, false, 'Hi, I\'m an expat living in Casablanca. Looking for traditional clothes for Eid'),
    i(66, 10, 20, true,  'Welcome! Great that you\'re embracing the culture. Do you know your size in Moroccan styles?'),
    i(66, 10, 40, false, 'Not sure — I\'m 185cm, medium build'),
    i(66, 11,  0, true,  'Definitely XL for Moroccan cut. Come in and we\'ll measure you properly, no obligation'),
    i(66, 11, 20, false, 'That\'s really helpful. I\'ll come Saturday'),
    i(66, 14,  0, false, 'Came in — the team was great! Bought a navy jellaba. Perfect fit'),
  ]),
  brief('Hamza Malik', '447700900004', [
    i(63, 15,  0, false, 'Salam! I\'m Moroccan living in Manchester. My mum asked me to order jellabas for the family'),
    i(63, 15, 20, true,  'Wa alaykum salam Hamza! We can help — how many pieces and what sizes?'),
    i(63, 15, 40, false, 'One for my dad (XL), one for my mum (L), two for my sisters (M and S)'),
    i(63, 16,  0, true,  '4 pieces total. Shall I put together a selection and send you photos?'),
    i(63, 16, 20, false, 'Yes please! Budget about 1500 DH for all four'),
    i(63, 16, 40, true,  'Totally doable. Sending photos now — mix of classic styles your parents will love'),
  ]),
  brief('Charlotte Bernard', '33612345678', [
    i(58, 11,  0, false, 'Bonjour! Je suis française mais j\'adore le style marocain. Livraison en France?'),
    i(58, 11, 20, true,  'Bonjour Charlotte! Oui, France 7-10 jours, 180 DH livraison'),
    i(58, 11, 40, false, 'Super! Je voudrais un caftan pour le mariage de mon amie marocaine'),
    i(58, 12,  0, true,  'Quelle belle occasion! Quel est votre budget?'),
    i(58, 12, 20, false, 'Entre 1000 et 1500 DH'),
    i(58, 12, 40, true,  'Parfait! Nous avons une belle sélection. Je vous envoie notre lookbook mariage'),
  ]),
  brief('Alex Chen', '447700900005', [
    i(54, 9,  0, false, 'Hi! I run a multicultural fashion store in Birmingham. Interested in stocking Moroccan pieces'),
    i(54, 9, 20, true,  'Hello Alex! That sounds great. What type of pieces are your customers asking for?'),
    i(54, 9, 40, false, 'Mainly caftans and kaftans for special occasions. Women\'s sizes 8-18 UK'),
    i(54, 10,  0, true,  'We have a full range. Our wholesale minimum is 20 pieces per style. Interested?'),
    i(54, 10, 20, false, 'Yes — can we start with a trial order of 30 mixed pieces?'),
    i(54, 10, 40, true,  'Absolutely. Let me send you our wholesale catalogue and terms sheet'),
  ]),
  brief('Yasmin Al-Farsi', '966501234567', [
    i(50, 16,  0, false, 'Hello, I\'m in Riyadh. Do you have abayas or long modest caftans?'),
    i(50, 16, 20, true,  'Hello Yasmin! We have beautiful long caftans that are very modest — full coverage with gorgeous embroidery'),
    i(50, 16, 40, false, 'Do you have them in black or dark navy?'),
    i(50, 17,  0, true,  'Yes, several in black with gold embroidery. Very popular in the Gulf. Shipping to KSA is 12-15 days'),
    i(50, 17, 20, false, 'I\'ll take 2 — one for me and one for my sister. Can we do different embroidery on each?'),
    i(50, 17, 40, true,  'Of course! Each piece is made to order. I\'ll send you embroidery pattern options'),
  ]),
  brief('Lisa Hoffman', '49151234567', [
    i(47, 13,  0, false, 'Guten Tag! I speak English — do you? I visited Morocco last year and fell in love with caftans'),
    i(47, 13, 20, true,  'Hello Lisa! Yes, we speak English! So glad you love our style. Are you looking to order?'),
    i(47, 13, 40, false, 'Yes! I want to give my friends caftans as gifts. 3 pieces, different sizes. Ship to Germany?'),
    i(47, 14,  0, true,  'We ship to Germany, about 10-12 days, 200 DH shipping. What are the sizes?'),
    i(47, 14, 20, false, 'S, M and L. Budget 400-600 DH each. Bright colours please!'),
    i(47, 14, 40, true,  'Perfect! We have vibrant summer colours — yellow, coral and turquoise. Sending photos now'),
  ]),
  // ── More Moroccan contacts ───────────────────────────────────────────────────
  brief('Mounia Lahlou', '212661200002', [
    i(93, 11,  0, false, 'السلام، واش عندكم شي كوليكسيون ديال الخريف؟'),
    i(93, 11, 20, true,  'أيه وصلتنا أقمشة دافية للخريف، جلابيب صوف وقفاطن بنقشات جديدة'),
    i(93, 11, 40, false, 'بغيت نشوف الصوف، شحال الثمن؟'),
    i(93, 12,  0, true,  'الصوف الجوتي من 500 إلى 750 حسب الموديل'),
    i(93, 12, 20, false, 'مزيان، غادي نجي الأسبوع الجاي'),
  ]),
  brief('Fouad Idrissi', '212661200003', [
    i(91, 9,  0, false, 'Bonjour! Proposez-vous des tenues pour baptêmes?'),
    i(91, 9, 20, true,  'Bonjour! Oui, tenues bébé et parents coordonnées. Très beau pour les photos'),
    i(91, 9, 40, false, 'Parfait! Bébé 6 mois, parents taille M/38. Budget 1200 DH pour les 3'),
    i(91, 10,  0, true,  'C\'est faisable! Nous proposons des ensembles coordonnés, très élégants'),
    i(91, 10, 20, false, 'Je viens samedi avec ma femme pour choisir'),
  ]),
  brief('Imane Cherkaoui', '212661200004', [
    i(89, 14,  0, false, 'مساء الخير، شريت عندكم قفطان الشهر الماضي والجودة ممتازة'),
    i(89, 14, 20, true,  'مساء النور إيمان! يسعدنا ذلك، شكرا لثقتك'),
    i(89, 14, 40, false, 'بغيت نطلب واحد آخر هاد الأسبوع للعيد، واش كاين تخفيض للزبون المخلص؟'),
    i(89, 15,  0, true,  'نعم! للزبائن المخلصين 15% تخفيض على طلب ثاني'),
    i(89, 15, 20, false, 'ممتاز! غادي نجي الغد'),
  ]),
  brief('Simo Bennis', '212661200005', [
    i(87, 10,  0, false, 'السلام، بغيت نعرف اش الفرق بين الجلابة المغربية والجزائرية؟'),
    i(87, 10, 20, true,  'سؤال ممتاز! الجزائرية عادةً أضيق وبقطع مختلفة، المغربية أوسع وبالتطريز اليدوي على الصدر والأكمام'),
    i(87, 10, 40, false, 'إذن المغربية أناقة أكثر؟'),
    i(87, 11,  0, true,  'في نظري الشخصي نعم! وهذا اختيارنا لكوليكسيوننا'),
    i(87, 11, 20, false, 'مقتنع! غادي نجي نشوف'),
  ]),
  brief('Meriem Fassi', '212661200006', [
    i(84, 16,  0, false, 'Bonsoir! Je cherche une tenue pour la cérémonie du henné de ma sœur'),
    i(84, 16, 20, true,  'Bonsoir Meriem! Pour le henné, nous avons des robes et caftans en couleurs vives — rouge, jaune, vert'),
    i(84, 16, 40, false, 'J\'aime le jaune doré. Taille 36'),
    i(84, 17,  0, true,  'Parfait pour un henné! Nous avons un magnifique caftan jaune doré brodé. 980 DH'),
    i(84, 17, 20, false, 'C\'est dans mon budget. Je réserve?'),
    i(84, 17, 40, true,  'Oui! Je note votre nom. Venez voir et si ça vous plaît on finalise'),
  ]),
  brief('Anas Benkirane', '212661200007', [
    i(81, 9,  0, false, 'السلام، كاين عندكم اختيارات للرجال غير الجلابة؟'),
    i(81, 9, 20, true,  'أهلاً أنس! نعم، قفاطن رجالية، سلهام، وبرانس للمناسبات'),
    i(81, 9, 40, false, 'مزيان، البرنس بالأخص، شحال ثمنه؟'),
    i(81, 10,  0, true,  'البرنس من 800 إلى 1500 حسب القماش والتطريز'),
    i(81, 10, 20, false, 'بغيت واحد للعرس الشهر الجاي، يمكنني نجي نشوفه؟'),
    i(81, 10, 40, true,  'بلا مشكيل، ننتظرك في أي وقت'),
  ]),
  brief('Zineb Sekkouri', '212661200008', [
    i(79, 11,  0, false, 'Salam! J\'organise un défilé de mode artisanal. Intéressés à exposer?'),
    i(79, 11, 20, true,  'Salam Zineb! Oui, très intéressés! Quel est le concept?'),
    i(79, 11, 40, false, 'Un défilé mettant en valeur l\'artisanat marocain moderne, 200 invités'),
    i(79, 12,  0, true,  'C\'est exactement notre positionnement! Combien de pièces souhaitez-vous?'),
    i(79, 12, 20, false, 'Une dizaine de pièces emblématiques. C\'est gratuit, visibilité en échange'),
    i(79, 12, 40, true,  'Intéressant! Pouvez-vous venir qu\'on en discute autour d\'un café?'),
  ]),
  brief('Khalil Amrani', '212661200009', [
    i(76, 13,  0, false, 'مرحبا، واش تقدرو تدير لي ثوب سلهام بنفس قماش الجلابة اللي شريت؟'),
    i(76, 13, 20, true,  'أهلاً خليل! نعم، هاد الخدمة ممكنة لكن نحتاج شوية وقت - أسبوعين تقريباً'),
    i(76, 13, 40, false, 'مزيان، شحال التكلفة الزيادة؟'),
    i(76, 14,  0, true,  'السلهام وحده من 400 إلى 600 حسب التطريز'),
    i(76, 14, 20, false, 'غادي ناخد الواحد بالتطريز، متفقين'),
  ]),
  brief('Ilham Tazi', '212661200010', [
    i(73, 15,  0, false, 'Bonjour! Je veux offrir un bon d\'achat à ma mère pour son anniversaire'),
    i(73, 15, 20, true,  'Bonjour Ilham! Quelle belle idée! Quel montant souhaitez-vous mettre?'),
    i(73, 15, 40, false, 'Entre 500 et 800 DH'),
    i(73, 16,  0, true,  'Parfait! Nous faisons des cartes cadeaux avec emballage élégant. Livraison possible aussi'),
    i(73, 16, 20, false, 'Vous livrez à Fès?'),
    i(73, 16, 40, true,  'Oui! 3-4 jours, 55 DH. La carte sera dans un bel emballage cadeau'),
  ]),
  brief('Yousra Mansouri', '212661200011', [
    i(69, 10,  0, false, 'السلام، كاين جلابة للأطفال كيمشيو بيها للمسجد؟'),
    i(69, 10, 20, true,  'أهلاً! نعم، عندنا جلابة ولاد بيضاء أو بيج، من مقاس 4 سنين'),
    i(69, 10, 40, false, 'الولد عندو 7 سنين، شحال المقاس؟'),
    i(69, 11,  0, true,  'المقاس 7-8 سنين - 170 درهم للجلابة البيضاء'),
    i(69, 11, 20, false, 'معقولة! غادي نجي مع الولد باش يجرب'),
  ]),
  brief('Kamal Doukkali', '212661200012', [
    i(67, 9,  0, false, 'Bonjour! Je suis tailleur, cherche du tissu jacquard pour confection'),
    i(67, 9, 20, true,  'Bonjour! Nous vendons principalement des pièces finies, pas de tissu au mètre malheureusement'),
    i(67, 9, 40, false, 'Dommage! Vous connaissez des fournisseurs de tissu?'),
    i(67, 10,  0, true,  'Je peux vous orienter vers quelques fournisseurs de Derb Omar à Casa'),
    i(67, 10, 20, false, 'Ce serait très gentil, merci beaucoup!'),
  ]),
  brief('Fatima Ait Brahim', '212661200013', [
    i(64, 14,  0, false, 'السلام، أنا من ورزازات، واش تبعتو للمدن البعيدة؟'),
    i(64, 14, 20, true,  'وعليكم السلام! نعم نبعتو لكل المغرب، ورزازات 4-6 أيام، التوصيل 65 درهم'),
    i(64, 14, 40, false, 'ممتاز! بغيت قفطان للزواج، اللون الأحمر'),
    i(64, 15,  0, true,  'عندنا قفاطن حمراء ممتازة للأعراس. بغيتي شوفي صور أولاً؟'),
    i(64, 15, 20, false, 'أيه! بعثيلي على واتساب'),
  ]),
  brief('Hassan Benali', '212661200014', [
    i(61, 10,  0, false, 'السلام، هل أنتم قريبون من محطة القطار؟'),
    i(61, 10, 20, true,  'أهلاً! نعم، 10 دقائق سيراً من محطة Casa Voyageurs'),
    i(61, 10, 40, false, 'كامل! غادي نجي من مراكش بالقطار الجمعة'),
    i(61, 11,  0, true,  'نستقبلك! نفتحو من 9ص حتى 8م، حتى الجمعة'),
    i(61, 11, 20, false, 'شكرا، غادي نجي الضحى'),
  ]),
  brief('Meryem Raji', '212661200015', [
    i(57, 16,  0, false, 'Bonsoir! Mon mari cherche un cadeau pour notre anniversaire. Il pense à un caftan'),
    i(57, 16, 20, true,  'Bonsoir Meryem! C\'est très attentionné de sa part! Quelle est votre taille?'),
    i(57, 16, 40, false, 'Taille 38, j\'aime les couleurs douces et le style élégant'),
    i(57, 17,  0, true,  'Je vais préparer une sélection spéciale pour lui. Il peut venir avec vous ou seul?'),
    i(57, 17, 20, false, 'Il viendra seul pour la surprise! Je lui transmets vos infos'),
    i(57, 17, 40, true,  'On s\'occupera bien de lui! On gardera le secret.'),
  ]),
  brief('Abdellah Skali', '212661200016', [
    i(55, 11,  0, false, 'السلام، أنا تاجر في فاس وبغيت نعرف إذا كاين إمكانية التعاون'),
    i(55, 11, 20, true,  'أهلاً عبد الله! ما طبيعة التعاون اللي بغيتي؟'),
    i(55, 11, 40, false, 'أنا عندي محل ملابس تقليدية في فاس، بغيت نبيع منتجاتكم'),
    i(55, 12,  0, true,  'فكرة ممتازة! نعمل مع تجار في عدة مدن. الشراء بالجملة بتخفيض 20-25%'),
    i(55, 12, 20, false, 'مزيان! متى يمكنني نزور المحل لنشوف الكوليكسيون؟'),
  ]),
  brief('Nicole Dupont', '33698765432', [
    i(53, 14,  0, false, 'Bonjour! Je reviens du Maroc et je veux commander en ligne ce que j\'ai vu dans votre boutique'),
    i(53, 14, 20, true,  'Bonjour Nicole! Bienvenue de retour! Qu\'est-ce qui vous a intéressée?'),
    i(53, 14, 40, false, 'Le caftan bordeaux en velours — j\'ai pris une photo. CF-412 je crois'),
    i(53, 15,  0, true,  'Très bon choix! Le CF-412 bordeaux velours. Quelle taille?'),
    i(53, 15, 20, false, 'Taille 40. Je paie comment depuis la France?'),
    i(53, 15, 40, true,  'Virement international ou Western Union. Je vous envoie tous les détails'),
  ]),
  brief('Mustapha Bennani', '212661200017', [
    i(51, 9,  0, false, 'السلام، بغيت نشتري هدايا للزملاء الأجانب، شي هدايا مغربية أصيلة'),
    i(51, 9, 20, true,  'أهلاً مصطفى! فكرة ممتازة! عندنا سكارف حرير، حقائب صغيرة مطرزة، وقفاطن صغيرة'),
    i(51, 9, 40, false, 'كم هدية ببال إلى 10 أشخاص، ميزانية 200-300 درهم للهدية'),
    i(51, 10,  0, true,  'ممتاز! عندنا طقم هدايا أنيق - سكارف + حقيبة صغيرة في علبة هدايا، 250 درهم'),
    i(51, 10, 20, false, 'ممتاز! غادي نطلب 10 منها'),
  ]),
];

// All 85 contacts for sync animation
const ALL_CONTACTS = [...ACTIVE, ...PASSIVE];

module.exports = { ACTIVE, PASSIVE, ALL_CONTACTS };
